/*
 * Parallax Classic v1.5
 *
 * Copyright 2012-2017, LambertGroup
 * 
*/


(function(d){function Y(a,b,c){var g=R();c.responsive&&(newCss="",-1!=a.css("font-size").lastIndexOf("px")?(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("px")),newCss+="font-size:"+fontSize/(c.origWidth/c.width)+"px;"):-1!=a.css("font-size").lastIndexOf("em")&&(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("em")),newCss+="font-size:"+fontSize/(c.origWidth/c.width)+"em;"),-1!=a.css("line-height").lastIndexOf("px")?(lineHeight=a.css("line-height").substr(0,
a.css("line-height").lastIndexOf("px")),newCss+="line-height:"+lineHeight/(c.origWidth/c.width)+"px;"):-1!=a.css("line-height").lastIndexOf("em")&&(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("em")),newCss+="line-height:"+lineHeight/(c.origWidth/c.width)+"em;"),a.wrapInner('<div class="newFS" style="'+newCss+'" />'));var f,r;f=a.attr("data-final-left");r=a.attr("data-final-top");c.responsive&&(f=parseInt(f/(c.origWidth/c.width),10),r=parseInt(r/(c.origWidth/c.width),
10));if("true"!=a.attr("data-preanimate")){var h=c.defaultEasing;""!=a.attr("data-easing")&&void 0!=a.attr("data-easing")&&(h=a.attr("data-easing"));c=1;1==b.isVideoPlaying&&(c=0);-1!=g&&9>g&&a.css({opacity:1});a.stop().animate({opacity:c,left:f+"px",top:r+"px"},1E3*a.attr("data-duration"),h,function(){1==b.isVideoPlaying&&d(b.currentImg.attr("data-text-id")).children().css("opacity",0)})}else a.css({left:f+"px",top:r+"px",opacity:1})}function S(a,b,c,g,f,r,h){b=d(b.attr("data-text-id")).children();
var m,v,t=0;currentText_arr=[];h&&d(".newFS",f).contents().unwrap();b.each(function(){currentText_arr[t]=d(this);var b=currentText_arr[t];h&&"true"==b.attr("data-preanimate")?(b.css({display:"block"}),m=b.attr("data-final-left"),v=b.attr("data-final-top"),c.responsive&&(m=parseInt(m/(c.origWidth/c.width),10),v=parseInt(v/(c.origWidth/c.width),10)),b.css({left:m+"px",top:v+"px",opacity:1,display:"block"})):h?b.css({display:"none",opacity:0}):b.css({display:"block"});"true"!=b.attr("data-preanimate")&&
(m=b.attr("data-initial-left"),v=b.attr("data-initial-top"),c.responsive&&(m=parseInt(m/(c.origWidth/c.width),10),v=parseInt(v/(c.origWidth/c.width),10)),b.css({left:m+"px",top:v+"px",opacity:parseInt(b.attr("data-fade-start"),10)/100}));h||(a.timeouts_arr[a.timeouts_arr.length]=setTimeout(function(){Y(b,a,c)},1E3*b.attr("data-delay")));t++})}function Z(a,b,c,g){c=d(a.currentImg.attr("data-text-id")).children();var f=0;currentText_arr=[];c.each(function(){currentText_arr[f]=d(this);var c=currentText_arr[f],
g=b.defaultExitLeft;void 0!=c.attr("data-exit-left")&&""!=c.attr("data-exit-left")&&(g=parseInt(c.attr("data-exit-left")/(b.origWidth/b.width),10));var m=b.defaultExitTop;void 0!=c.attr("data-exit-top")&&""!=c.attr("data-exit-top")&&(m=parseInt(c.attr("data-exit-top")/(b.origWidth/b.width),10));var v=b.defaultExitDuration;void 0!=c.attr("data-exit-duration")&&""!=c.attr("data-exit-duration")&&(v=parseFloat(c.attr("data-exit-duration")));var t=b.defaultExitDelay;void 0!=c.attr("data-exit-delay")&&
""!=c.attr("data-exit-delay")&&(t=parseFloat(c.attr("data-exit-delay")));var w=b.defaultExitEasing;void 0!=c.attr("data-exit-easing")&&""!=c.attr("data-exit-easing")&&(w=c.attr("data-exit-easing"));var l=b.defaultExitOFF.toString();void 0!=c.attr("data-exit-off")&&""!=c.attr("data-exit-off")&&(l=c.attr("data-exit-off"));"true"==l&&(v=0);0<v&&parseInt(c.attr("data-final-top")/(b.origWidth/b.width),10)==parseInt(c.css("top").substr(0,c.css("top").lastIndexOf("px")),10)?a.timeouts_arr[a.timeouts_arr.length]=
setTimeout(function(){c.stop().animate({left:g+"px",top:m+"px"},1E3*v,w,function(){"true"!=c.attr("data-preanimate")&&"false"==l?c.css({display:"none"}):(theLeft=c.attr("data-final-left"),theTop=c.attr("data-final-top"),b.responsive&&(theLeft=parseInt(theLeft/(b.origWidth/b.width),10),theTop=parseInt(theTop/(b.origWidth/b.width),10)),c.css({left:theLeft+"px",top:theTop+"px",opacity:1}))})},1E3*t):"true"!=c.attr("data-preanimate")&&"false"==l&&c.css({display:"none"});f++})}function V(a,b,c,g){for(k=
0;k<g;k++)c=d(a[k]),c=d(c.attr("data-text-id")).children(),currentText_arr=[],c.each(function(){currentText_arr[0]=d(this);var a=currentText_arr[0];if("true"==a.attr("data-preanimate")){a.css({display:"block"});var c=a.attr("data-final-left"),g=a.attr("data-final-top");b.responsive&&(c=parseInt(c/(b.origWidth/b.width),10),g=parseInt(g/(b.origWidth/b.width),10));a.css({left:c+"px",top:g+"px",opacity:1})}else a.css({display:"none"})})}function L(a){if(a)for(var b in a)a[b]&&clearTimeout(a[b]);a.length=
0}function I(a,b,c,g,f,r,h,m,v,t,w,l,B,G,H,u,J,z){var x=!0,y;if(!c.loop&&b.current_img_no+a>=g||!c.loop&&0>b.current_img_no+a)x=!1;x&&!b.slideIsRunning&&b.firstLoadingComplete&&(b.slideIsRunning=!0,L(b.timeouts_arr),y=b.previous_current_img_no,d(b.currentImg.attr("data-text-id")).children().clearQueue(),Z(b,c,h,m),c.showCircleTimer&&(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=c.behindCircleAlpha/100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+
2*c.circleLineWidth,c.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=c.circleLineWidth+2,b.ctx.strokeStyle=c.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=c.circleAlpha/100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,0,!1),b.ctx.lineWidth=c.circleLineWidth,b.ctx.strokeStyle=c.circleColor,b.ctx.stroke()),"bullets"==c.skin?d(f[b.current_img_no]).removeClass("bottomNavButtonON"):d(l[b.current_img_no]).removeClass("thumbsHolder_ThumbON"),
w.css("display","none"),b.current_img_no=b.current_img_no+a>=g?0:0>b.current_img_no+a?g-1:b.current_img_no+a,c.showBottomNav&&("bullets"==c.skin?(c.autoHideBottomNav||z.css("display","block"),d(f[b.current_img_no]).addClass("bottomNavButtonON")):(c.autoHideBottomNav||J.css("display","block"),d(l[b.current_img_no]).addClass("thumbsHolder_ThumbON"),currentCarouselLeft=B.css("left").substr(0,B.css("left").lastIndexOf("px")),0===b.current_img_no||b.current_img_no===g-1?O(0,B,G,H,c,g,u,b):O(1001,B,G,H,
c,g,u,b))),b.currentImg=d(r[b.current_img_no]),v.animate({left:-1*b.current_img_no*c.width+"px"},1E3*c.scrollSlideDuration,c.scrollSlideEasing,function(){b.slideIsRunning=!1;b.arcInitialTime=(new Date).getTime();b.timeElapsed=0;"true"==d(r[b.current_img_no]).attr("data-video")&&w.css("display","block");"true"==d(r[b.previous_current_img_no]).attr("data-video")&&(d("#contentHolderUnit_"+b.previous_current_img_no,t).html(d(r[b.previous_current_img_no]).html()),W(b.previous_current_img_no,b,c,r,t,h,
m));L(b.timeouts_arr);S(b,d(r[y]),c,h,t,m,!0);S(b,b.currentImg,c,h,t,m,!1);0<c.autoPlay&&1<g&&!b.mouseOverBanner&&(clearTimeout(b.timeoutID),b.timeoutID=setTimeout(function(){b.previous_current_img_no=b.current_img_no;I(1,b,c,g,f,r,h,m,v,t,w,l,B,G,H,u,J,z)},1E3*c.autoPlay))}))}function P(a,b,c,d,f){b=c.origImgsDimensions[b].split(";");d.responsive&&(b[0]/=d.origWidth/d.width,b[1]/=d.origWidth/d.width);a.width(b[0]);a.height(b[1]);f&&d.width100Proc&&d.height100Proc&&a.css({position:"relative",left:parseInt(d.width-
a.width(),10)+"px",top:parseInt(d.height-a.height(),10)+"px"})}function W(a,b,c,g,f,r,h){c.responsive&&(imgInside=d("#contentHolderUnit_"+a,f).find("img:first"),null!=imgInside.width()&&P(imgInside,a,b,c,!0),textIdChildren=d(d(g[a]).attr("data-text-id")).children(),k=-1,textIdChildren.each(function(){k++;imgInside=d(this).find("img:first");null!=imgInside.width()&&P(imgInside,d(g[a]).attr("data-text-id")+"-"+k,b,c,!1)}),d(d(g[a]).attr("data-text-id")).css({width:c.width+"px",left:parseInt(a*c.width,
10),top:h.css("top")}))}function O(a,b,d,g,f,r,h,m){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));1===a||-1===a?(m.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:"+="+a*m.carouselStep},500,"easeOutCubic",function(){M(m,b,d,g,f,r,h);m.isCarouselScrolling=!1})):currentCarouselLeft!=-1*Math.floor(m.current_img_no/f.numberOfThumbsPerScreen)*m.carouselStep&&(m.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:-1*Math.floor(m.current_img_no/
f.numberOfThumbsPerScreen)*m.carouselStep},500,"easeOutCubic",function(){M(m,b,d,g,f,r,h);m.isCarouselScrolling=!1}))}function M(a,b,d,g,f,r,h){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));0>currentCarouselLeft?d.hasClass("carouselLeftNavDisabled")&&d.removeClass("carouselLeftNavDisabled"):d.addClass("carouselLeftNavDisabled");Math.abs(currentCarouselLeft-a.carouselStep)<(h.width()+a.thumbMarginLeft)*r?g.hasClass("carouselRightNavDisabled")&&g.removeClass("carouselRightNavDisabled"):
g.addClass("carouselRightNavDisabled")}function X(a,b,c,g,f,r,h,m,v,t,w){"thumbs"==b.skin&&(w.css({bottom:parseInt(b.thumbsWrapperMarginBottom/(b.origWidth/b.width),10)+"px",top:"auto",height:parseInt(b.origthumbsHolderWrapperH/(b.origWidth/b.width),10)+"px"}),bgTopCorrection=0,h.css("background-position","0px "+((w.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px"),m.css("background-position","0px "+((w.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px"),t.css("width",b.width-
h.width()-m.width()),b.origWidthThumbsHolderVisibleWrapper=b.origWidth-h.width()-m.width(),f.css({width:parseInt(b.origThumbW/(b.origWidthThumbsHolderVisibleWrapper/t.width()),10)+"px",height:parseInt(b.origThumbH/(b.origWidthThumbsHolderVisibleWrapper/t.width()),10)+"px"}),b.numberOfThumbsPerScreen>=c&&t.css("left",parseInt((w.width()-(v.width()+a.thumbMarginLeft)*c)/2,10)+"px"),d(".thumbsHolder_ThumbOFF",g).find("img:first").css({width:f.width()+"px",height:f.height()+"px","margin-top":parseInt((w.height()-
f.height())/2,10)+"px"}),a.thumbMarginLeft=Math.floor((w.width()-h.width()-m.width()-v.width()*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1)),thumb_i=-1,r.children().each(function(){thumb_i++;theThumb=d(this);theThumb.css("background-position","center "+b.thumbsOnMarginTop/(b.origWidth/b.width)+"px");0>=thumb_i?theThumb.css("margin-left",Math.floor((w.width()-h.width()-m.width()-(a.thumbMarginLeft+theThumb.width())*(b.numberOfThumbsPerScreen-1)-theThumb.width())/2)+"px"):theThumb.css("margin-left",
a.thumbMarginLeft+"px")}),a.carouselStep=(v.width()+a.thumbMarginLeft)*b.numberOfThumbsPerScreen)}function R(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,10)}d.fn.parallax_classic=function(a){a=d.extend({},d.fn.parallax_classic.defaults,a);return this.each(function(){var b=d(this);responsiveWidth=b.parent().width();responsiveHeight=b.parent().height();a.responsiveRelativeToBrowser&&
(responsiveWidth=d(window).width(),responsiveHeight=d(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/a.origHeight)));var c=d("<div></div>").addClass("parallax_classic").addClass(a.skin),g=d('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>    </div>  <div class="contentHolderVisibleWrapper"><div class="contentHolder"></div></div>   <div class="playOver"></div>  <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>  <canvas class="mycanvas"></canvas>');
b.wrap(c);b.after(g);var f=b.parent(".parallax_classic"),g=d(".bannerControls",f),r=d(".contentHolderVisibleWrapper",f),h=d(".contentHolder",f),c=d('<div class="bottomNavLeft"></div>'),m=d('<div class="bottomNav"></div>'),v=d('<div class="bottomNavRight"></div>');b.after(c);b.after(m);b.after(v);a.showAllControllers||g.css("display","none");var t=d(".leftNav",f),w=d(".rightNav",f);t.css("display","none");w.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(t.css("display","block"),w.css("display",
"block"));var l=d(".bottomNav",f),B=d(".bottomNavLeft",f),G=d(".bottomNavRight",f),H;l.css("display","block");B.css("display","block");G.css("display","block");l.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});B.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});G.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});a.showBottomNav||(l.css("display","none"),B.css("display",
"none"),G.css("display","none"));a.showOnInitBottomNav||(l.css("left","-5000px"),B.css("left","-5000px"),G.css("left","-5000px"));var u=d(".thumbsHolderWrapper",f),J=d(".thumbsHolderVisibleWrapper",f),z=d(".thumbsHolder",f),x,y;x=d('<div class="carouselLeftNav"></div>');y=d('<div class="carouselRightNav"></div>');u.append(x);u.append(y);y.css("right","0");z.css("width",x.width()+"px");a.showBottomNav&&a.showOnInitBottomNav||u.css({opacity:0,display:"none"});"thumbs"==a.skin&&u.css({bottom:parseInt(a.thumbsWrapperMarginBottom/
(a.origWidth/a.width),10)+"px",top:"auto"});a.enableTouchScreen&&f.swipe({swipe:function(a,b,d,c,f){e.effectIsRunning||("right"==b?t.click():w.click())}});var C=d(".playOver",f);C.css({left:parseInt((a.width-C.width())/2,10)+"px",top:parseInt((a.height-C.height())/2,10)+"px"});d(".myloader",f).css({left:(a.width-d(".myloader",f).width())/2+"px",top:(a.height-d(".myloader",f).height())/2+"px"});var q=0,e={current_img_no:0,currentImg:0,previous_current_img_no:0,slideIsRunning:!1,mouseOverBanner:!1,
isVideoPlaying:!1,carouselStep:0,thumbMarginLeft:0,timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,windowWidth:0,origImgsDimensions:[],firstLoadingComplete:!1,canvas:"",ctx:"",timeouts_arr:[],bannerRatio:a.origWidth/a.origHeight},T=0;e.canvas=d(".mycanvas",f)[0];e.canvas.width=2*a.circleRadius+4*a.circleLineWidth;e.canvas.height=2*a.circleRadius+4*a.circleLineWidth;c=R();-1!=c&&9>c&&(a.showCircleTimer=!1);a.showCircleTimer&&(e.ctx=e.canvas.getContext("2d"));f.width(a.width);
f.height(a.height);r.width(a.width);r.height(a.height);h.width(a.width);h.height(a.height);g.css("margin-top",parseInt((a.height-t.height())/2,10)+"px");var p=b.find("ul:first").children(),K,L=0,E,A,Q=0,M=0,D;p.each(function(){e.currentImg=d(this);e.currentImg.is("li")||(e.currentImg=e.currentImg.find("li:first"));if(e.currentImg.is("li")){q++;K=d('<div class="contentHolderUnit" rel="'+(q-1)+'" id="contentHolderUnit_'+(q-1)+'">'+e.currentImg.html()+"</div>");K.width(a.width);K.height(a.height);h.append(K);
L+=a.width;D=d("#contentHolderUnit_"+(q-1),f).find("img:first");null!=D.width()?(e.origImgsDimensions[q-1]=D.width()+";"+D.height(),a.responsive&&a.origWidth!=responsiveWidth&&P(D,q-1,e,a,!0)):e.origImgsDimensions[q-1]=null;"bullets"==a.skin?(E=d('<div class="bottomNavButtonOFF" rel="'+(q-1)+'"></div>'),l.append(E),Q+=parseInt(E.css("padding-left").substring(0,E.css("padding-left").length-2),10)+E.width(),M=parseInt((l.height()-parseInt(E.css("height").substring(0,E.css("height").length-2)))/2,10),
E.css("margin-top",M+"px")):(image_name=d(p[q-1]).attr("data-bottom-thumb"),A=d('<div class="thumbsHolder_ThumbOFF" rel="'+(q-1)+'"><img src="'+image_name+'"></div>'),z.append(A),0==a.origThumbW&&(0==a.numberOfThumbsPerScreen&&(a.numberOfThumbsPerScreen=Math.floor((a.origWidth-x.width()-y.width())/A.width())),a.origThumbW=A.width(),a.origThumbH=A.height(),a.origthumbsHolderWrapperH=u.height(),e.thumbMarginLeft=Math.floor((a.origWidth-x.width()-y.width()-A.width()*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-
1))),z.css("width",z.width()+e.thumbMarginLeft+A.width()+"px"),thumbsHolder_MarginTop=parseInt((u.height()-parseInt(A.css("height").substring(0,A.css("height").length-2)))/2,10));h.append(d(e.currentImg.attr("data-text-id")));d(e.currentImg.attr("data-text-id")).css({width:a.width+"px",height:"100%",overflow:"hidden",left:parseInt((q-1)*a.width,10),top:g.css("top")});var b=-1;d(e.currentImg.attr("data-text-id")).children().each(function(){b++;D=d(this).find("img:first");null!=D.width()?(e.origImgsDimensions[e.currentImg.attr("data-text-id")+
"-"+b]=D.width()+";"+D.height(),a.responsive&&a.origWidth!=responsiveWidth&&P(D,e.currentImg.attr("data-text-id")+"-"+b,e,a,!1)):e.origImgsDimensions[e.currentImg.attr("data-text-id")+"-"+b]=null})}});h.width(L);"bullets"==a.skin?(l.width(Q),a.showOnInitBottomNav&&(l.css("left",parseInt((f.width()-Q)/2,10)+"px"),B.css("left",parseInt(l.css("left").substring(0,l.css("left").length-2),10)-B.width()+"px"),G.css("left",parseInt(l.css("left").substring(0,l.css("left").length-2),10)+l.width()+parseInt(E.css("padding-left").substring(0,
E.css("padding-left").length-2),10)+"px"))):(J.css({width:a.origWidth-x.width()-y.width(),left:x.width()+"px"}),e.carouselStep=(A.width()+e.thumbMarginLeft)*a.numberOfThumbsPerScreen,x.addClass("carouselLeftNavDisabled"),a.numberOfThumbsPerScreen>=q&&(y.addClass("carouselRightNavDisabled"),x.css("display","none"),y.css("display","none"),J.css("left",parseInt((u.width()-(A.width()+e.thumbMarginLeft)*q)/2,10)+"px")),d(".thumbsHolder_ThumbOFF",f).find("img:first").css("margin-top",thumbsHolder_MarginTop+
"px"),a.origthumbsHolder_MarginTop=thumbsHolder_MarginTop);thumbsHolder_Thumbs=d(".thumbsHolder_ThumbOFF",f);X(e,a,q,f,thumbsHolder_Thumbs,z,x,y,A,J,u);d("iframe",f).each(function(){var a=d(this).attr("src"),b="?wmode=transparent";-1!=a.indexOf("?")&&(b="&wmode=transparent");d(this).attr("src",a+b)});e.current_img_no=0;e.currentImg=d(p[0]);f.mouseenter(function(){a.pauseOnMouseOver&&1<q&&e.firstLoadingComplete&&(e.mouseOverBanner=!0,clearTimeout(e.timeoutID),nowx=(new Date).getTime(),e.timeElapsed+=
nowx-e.arcInitialTime);a.autoHideNavArrows&&a.showNavArrows&&(t.css("display","block"),w.css("display","block"));a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?(l.css({display:"block",left:parseInt((f.width()-Q)/2,10)+"px"}),B.css({display:"block",left:parseInt(l.css("left").substring(0,l.css("left").length-2),10)-B.width()+"px"}),G.css({display:"block",left:parseInt(l.css("left").substring(0,l.css("left").length-2),10)+l.width()+parseInt(E.css("padding-left").substring(0,E.css("padding-left").length-
2),10)+"px"})):0>a.thumbsWrapperMarginBottom&&e.isVideoPlaying||!a.showBottomNav||(u.css({display:"block"}),u.stop().animate({opacity:1},500,"swing",function(){})))});f.mouseleave(function(){a.pauseOnMouseOver&&1<q&&e.firstLoadingComplete&&(e.mouseOverBanner=!1);a.autoHideNavArrows&&a.showNavArrows&&(t.css("display","none"),w.css("display","none"));a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?(l.css("display","none"),B.css("display","none"),G.css("display","none")):u.stop().animate({opacity:0},
300,"swing",function(){}));if(0<a.autoPlay&&1<q&&!e.isVideoPlaying&&a.pauseOnMouseOver&&e.firstLoadingComplete){clearTimeout(e.timeoutID);nowx=(new Date).getTime();e.arcInitialTime=(new Date).getTime();var d=parseInt(1E3*a.autoPlay-(e.timeElapsed+nowx-e.arcInitialTime),10);e.timeoutID=setTimeout(function(){I(1,e,a,q,F,p,b,g,h,f,C,thumbsHolder_Thumbs,z,x,y,A,u,l)},d)}});K=d(".contentHolderUnit",h);K.click(function(){var b=d(this).attr("rel");"true"==d(p[e.current_img_no]).attr("data-video")?b!=e.current_img_no?
e.isVideoPlaying=!1:(clearTimeout(e.timeoutID),D=d(this).find("img:first"),D.css("display","none"),C.css("display","none"),e.isVideoPlaying=!0,"thumbs"==a.skin&&a.thumbsWrapperMarginBottom>-1*a.origthumbsHolderWrapperH&&u.css("display","none"),"bullets"==a.skin&&0<=a.thumbsWrapperMarginBottom&&l.css("display","none")):void 0!=d(p[e.current_img_no]).attr("data-link")&&b==e.current_img_no&&""!=d(p[e.current_img_no]).attr("data-link")&&(b=a.target,void 0!=d(p[e.current_img_no]).attr("data-target")&&
""!=d(p[e.current_img_no]).attr("data-target")&&(b=d(p[e.current_img_no]).attr("data-target")),"_blank"==b?window.open(d(p[e.current_img_no]).attr("data-link")):window.location=d(p[e.current_img_no]).attr("data-link"))});C.click(function(){C.css("display","none");clearTimeout(e.timeoutID);D=d("#contentHolderUnit_"+e.current_img_no,f).find("img:first");D.css("display","none");e.isVideoPlaying=!0;"thumbs"==a.skin&&a.thumbsWrapperMarginBottom>-1*a.origthumbsHolderWrapperH&&u.css("display","none");"bullets"==
a.skin&&0<=a.thumbsWrapperMarginBottom&&l.css("display","none")});d(".parallax_classic_texts",f).click(function(){if(void 0!=d(p[e.current_img_no]).attr("data-link")&&""!=d(p[e.current_img_no]).attr("data-link")&&!e.slideIsRunning){var b=a.target;void 0!=d(p[e.current_img_no]).attr("data-target")&&""!=d(p[e.current_img_no]).attr("data-target")&&(b=d(p[e.current_img_no]).attr("data-target"));"_blank"==b?window.open(d(p[e.current_img_no]).attr("data-link")):window.location=d(p[e.current_img_no]).attr("data-link")}});
t.click(function(){e.slideIsRunning||(e.isVideoPlaying=!1,e.previous_current_img_no=e.current_img_no,clearTimeout(e.timeoutID),I(-1,e,a,q,F,p,b,g,h,f,C,thumbsHolder_Thumbs,z,x,y,A,u,l))});w.click(function(){e.slideIsRunning||(e.isVideoPlaying=!1,e.previous_current_img_no=e.current_img_no,clearTimeout(e.timeoutID),I(1,e,a,q,F,p,b,g,h,f,C,thumbsHolder_Thumbs,z,x,y,A,u,l))});var U=!1;d(window).resize(function(){var c=R();doResizeNow=!0;-1!=navigator.userAgent.indexOf("Android")&&(0==a.windowOrientationScreenSize0&&
0==window.orientation&&(a.windowOrientationScreenSize0=d(window).width()),0==a.windowOrientationScreenSize90&&90==window.orientation&&(a.windowOrientationScreenSize90=d(window).height()),0==a.windowOrientationScreenSize_90&&-90==window.orientation&&(a.windowOrientationScreenSize_90=d(window).height()),a.windowOrientationScreenSize0&&0==window.orientation&&d(window).width()>a.windowOrientationScreenSize0&&(doResizeNow=!1),a.windowOrientationScreenSize90&&90==window.orientation&&d(window).height()>
a.windowOrientationScreenSize90&&(doResizeNow=!1),a.windowOrientationScreenSize_90&&-90==window.orientation&&d(window).height()>a.windowOrientationScreenSize_90&&(doResizeNow=!1),0==e.windowWidth&&(doResizeNow=!1,e.windowWidth=d(window).width()));-1!=c&&9==c&&0==e.windowWidth&&(doResizeNow=!1);e.windowWidth==d(window).width()?(doResizeNow=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,doResizeNow=!0)):e.windowWidth=
d(window).width();a.responsive&&doResizeNow&&(!1!==U&&clearTimeout(U),U=setTimeout(function(){var c=e,n=a,N=q,m=g,v=F,w=thumbsHolder_Thumbs,B=A;responsiveWidth=b.parent().parent().width();responsiveHeight=b.parent().parent().height();n.responsiveRelativeToBrowser&&(responsiveWidth=d(window).width(),responsiveHeight=d(window).height());n.width100Proc&&(n.width=responsiveWidth);n.height100Proc&&(n.height=responsiveHeight);if(n.origWidth!=responsiveWidth||n.width100Proc){n.origWidth>responsiveWidth||
n.width100Proc?n.width=responsiveWidth:n.width100Proc||(n.width=n.origWidth);n.height100Proc||(n.height=n.width/c.bannerRatio);f.width(n.width);f.height(n.height);r.width(n.width);r.height(n.height);h.width(n.width);h.height(n.height);m.css("margin-top",parseInt((n.height-t.height())/2,10)+"px");V(p,n,b,N);contentHolderUnit=d(".contentHolderUnit",f);contentHolderUnit.width(n.width);contentHolderUnit.height(n.height);holderWidth=n.width*N;for(i=0;i<N;i++)W(i,c,n,p,f,b,m);h.width(holderWidth);"bullets"==
n.skin?0<=n.thumbsWrapperMarginBottom?l.css({left:parseInt((f.width()-l.width())/2,10)+"px",bottom:parseInt(n.thumbsWrapperMarginBottom/(n.origWidth/n.width),10)+"px",top:"auto"}):l.css({left:parseInt((f.width()-l.width())/2,10)+"px"}):X(c,n,N,f,w,z,x,y,B,J,u);C.css({left:parseInt((n.width-C.width())/2,10)+"px",top:parseInt((n.height-C.height())/2,10)+"px"});clearTimeout(c.timeoutID);I(1,c,n,N,v,p,b,m,h,f,C,w,z,x,y,B,u,l)}},300))});if("bullets"==a.skin){var F=d(".bottomNavButtonOFF",f);F.click(function(){if(!e.slideIsRunning&&
e.firstLoadingComplete){e.isVideoPlaying=!1;var c=d(this).attr("rel");e.current_img_no!=c&&(d(F[e.current_img_no]).removeClass("bottomNavButtonON"),e.previous_current_img_no=e.current_img_no,e.current_img_no=c-1,I(1,e,a,q,F,p,b,g,h,f,C,thumbsHolder_Thumbs,z,x,y,A,u,l))}});F.mouseenter(function(){var b=d(this),c=b.attr("rel");if(a.showPreviewThumbs){H=d('<div class="bottomOverThumb"></div>');b.append(H);var e=d(p[c]).attr("data-bottom-thumb"),f=d(p[T]).attr("data-bottom-thumb"),g=80,h=-80;T>c&&(g=
-80,h=80);H.html("");H.html('<div class="innerBottomOverThumb"><img src="'+f+'"style="margin:0px;" id="oldThumb"><img src="'+e+'" style="margin-top:-80px; margin-left:'+g+'px;" id="newThumb"></div>');d("#newThumb").stop().animate({marginLeft:"0px"},150,function(){H.html('<div class="innerBottomOverThumb"><img src="'+e+'"></div>')});d("#oldThumb").stop().animate({marginLeft:h+"px"},150,function(){});T=c}b.addClass("bottomNavButtonON")});F.mouseleave(function(){var b=d(this),c=b.attr("rel");a.showPreviewThumbs&&
H.remove();e.current_img_no!=c&&b.removeClass("bottomNavButtonON")})}thumbsHolder_Thumbs.mousedown(function(){arrowClicked=!0;if(!e.effectIsRunning&&e.firstLoadingComplete){e.isVideoPlaying=!1;var c=d(this).attr("rel");e.current_img_no!=c&&(d(thumbsHolder_Thumbs[e.current_img_no]).removeClass("thumbsHolder_ThumbON"),e.previous_current_img_no=e.current_img_no,e.current_img_no=c-1,I(1,e,a,q,F,p,b,g,h,f,C,thumbsHolder_Thumbs,z,x,y,A,u,l))}});thumbsHolder_Thumbs.mouseup(function(){arrowClicked=!1});thumbsHolder_Thumbs.mouseenter(function(){var a=
d(this);a.attr("rel");a.addClass("thumbsHolder_ThumbON")});thumbsHolder_Thumbs.mouseleave(function(){var a=d(this),b=a.attr("rel");e.current_img_no!=b&&a.removeClass("thumbsHolder_ThumbON")});x.click(function(){e.isCarouselScrolling||(currentCarouselLeft=z.css("left").substr(0,z.css("left").lastIndexOf("px")),0>currentCarouselLeft&&O(1,z,x,y,a,q,A,e))});y.click(function(){e.isCarouselScrolling||(currentCarouselLeft=z.css("left").substr(0,z.css("left").lastIndexOf("px")),Math.abs(currentCarouselLeft-
e.carouselStep)<(A.width()+e.thumbMarginLeft)*q&&O(-1,z,x,y,a,q,A,e))});"bullets"==a.skin?d(F[e.current_img_no]).addClass("bottomNavButtonON"):d(thumbsHolder_Thumbs[e.current_img_no]).addClass("thumbsHolder_ThumbON");setTimeout(function(){d(".myloader",f).css("display","none");V(p,a,b,q);e.firstLoadingComplete=!0;e.arcInitialTime=(new Date).getTime();e.mouseOverBanner=!1;e.timeElapsed=0;S(e,e.currentImg,a,b,f,g,!1,e.current_img_no);0<a.autoPlay&&1<q&&(a.showCircleTimer&&(e.intervalID=setInterval(function(){var b=
e,c=a;nowx=(new Date).getTime();b.mouseOverBanner||b.effectIsRunning||!c.showCircleTimer||b.slideIsRunning||(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=c.behindCircleAlpha/100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=c.circleLineWidth+2,b.ctx.strokeStyle=c.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=c.circleAlpha/100,b.ctx.arc(c.circleRadius+2*
c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,(b.timeElapsed+nowx-b.arcInitialTime)/1E3*2/c.autoPlay*Math.PI,!1),b.ctx.lineWidth=c.circleLineWidth,b.ctx.strokeStyle=c.circleColor,b.ctx.stroke())},125)),e.timeoutID=setTimeout(function(){I(1,e,a,q,F,p,b,g,h,f,C,thumbsHolder_Thumbs,z,x,y,A,u,l)},1E3*a.autoPlay))},1E3*a.myloaderTime);"true"==d(p[e.current_img_no]).attr("data-video")&&C.css("display","block")})};d.fn.parallax_classic.defaults={skin:"bullets",width:918,height:382,
width100Proc:!1,height100Proc:!1,autoPlay:7,loop:!0,target:"_blank",absUrl:"",showAllControllers:!0,showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!0,showBottomNav:!0,showOnInitBottomNav:!0,autoHideBottomNav:!0,showPreviewThumbs:!0,enableTouchScreen:!0,pauseOnMouseOver:!0,showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:10,circleLineWidth:4,circleColor:"#FF0000",circleAlpha:100,behindCircleColor:"#000000",behindCircleAlpha:50,responsive:!0,responsiveRelativeToBrowser:!1,thumbsWrapperMarginBottom:-35,
scrollSlideDuration:.8,scrollSlideEasing:"easeOutQuad",numberOfThumbsPerScreen:0,thumbsOnMarginTop:10,defaultEasing:"swing",myloaderTime:4,defaultExitLeft:0,defaultExitTop:0,defaultExitDuration:0,defaultExitDelay:0,defaultExitEasing:"swing",defaultExitOFF:!1,origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origthumbsHolderWrapperH:0,origWidthThumbsHolderVisibleWrapper:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
